### ISSUE TITLE
A question about code structure

### ISSUE THREAD

**Issue by gerchicov-bp** [heikomaass/HMLauncherView#11]
Could you explain why do you use the following variables at once:
@property (nonatomic, assign) BOOL canBeDeleted;
@property (nonatomic, assign) BOOL hideDeleteImage;

it seems hideDeleteImage is extra

**Comment by heikomaass** [comment]
They are not the same:

`canBeDeleted`: If set to `true`, the item can be deleted from the LauncherView. 
`hideDeleteImage`: A flag which indicates that the delete image should be hidden. When the LauncherView is in the editing mode, the delete image should be displayed and this flag is set to `false`.

The `hideDeleteImage` is part of the public interface of `HMLauncherIcon` because the `HMLauncherView` sets the state in its `updateDeleteButtons` method.
